# Generated by Django 4.0.3 on 2022-03-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
