# Generated by Django 4.0.3 on 2022-03-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
